name: WordPress Playground preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    name: Add Playground preview
    runs-on: ubuntu-latest

    steps:
      - name: Add preview button
        uses: WordPress/action-wp-playground-pr-preview@v3
        with:
          theme-path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
